DjangoEdi/urls.py
from django.contrib import admin
from django.urls import include, path
from service.views import tcpRequest
from main.views import startingThreads
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include("Login.urls")),
    path('index/', include("main.urls")),
]


try:
    print ("hello-1")
    startingThreads(repeat=5)
except KeyboardInterrupt:
    print("Service Ended !! ")


# try:
#     print ("hello-2")
#     statusReports(repeat=300)
# except KeyboardInterrupt:
#     print("Service Ended !! ")

Login/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'login'
urlpatterns = [
    # /login/
    url(r'^$', views.index, name="index"),
]

main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^creatingAccount/$', views.accountCreation, name="account"),
    url(r'^statusReport/$', views.statusReport, name="report"),
    url(r'^companyActiveLoads/$', views.activeLoads, name="activeLoads"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^generatingReport/$', views.generatingReport, name="generating_report"),
    url(r'^statusPaths/$', views.creatingStatusPaths, name="status_paths"),
    url(r'^loadsPaths/$', views.creatingLoadPaths, name="load_paths"),
    url(r'^establishingConnection/$', views.establishingConnection, name="establishingConnection"),
]

Login/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.conf import settings
import json
import socket
import schedule
import time
import glob
import datetime
import requests
from ast import literal_eval

def index(request):
    """ If the request is get it will return a login form , other wise it send a tcp login request to server. """
    if request.method == "GET":
        try:
            sessionData = request.session['name']
            return redirect("main:index")
        except Exception as e:
            return render(request, 'Login/index.html')

    elif request.method == "POST":
        python_dict = authentication(request)

        if(python_dict.get("access_token", "empty") != "empty"):    
            request.session['name'] = request.POST['username']
            request.session['token'] = python_dict.get("access_token", "empty")
            return redirect("main:index")
        else:
             return render(request, 'Login/index.html', {"error": "login credentials are not valid"})


def authentication(request):
    # It is used to authenticate the user/company and returns the request status.
    url = "http://35.167.129.201:8081/oauth/token"
    username= request.POST['username']
    password = request.POST['pass']
    payload = "grant_type=password&username=" + username + "&password=" + password + "&client_id=spring-security-oauth2-read-write-client&undefined="
    headers = {
        'Content-Type': "application/x-www-form-urlencoded",
        'Authorization': "Basic c3ByaW5nLXNlY3VyaXR5LW9hdXRoMi1yZWFkLXdyaXRlLWNsaWVudDpzcHJpbmctc2VjdXJpdHktb2F1dGgyLXJlYWQtd3JpdGUtY2xpZW50LXBhc3N3b3JkMTIzNA==",
        'cache-control': "no-cache",
        }
    response = requests.request("POST", url, data=payload, headers=headers)
    return  literal_eval(response.text)
    

def settingCookie(cookieName,request, response):
    """ Setting the cookie to store the email of the login id and then use it to fetch all comapnies."""
    response.set_cookie(cookieName, request)


def set_cookie(response, key, value, days_expire=7):
    if days_expire is None:
        max_age = 365 * 24 * 60 * 60  # one year
    else:
        max_age = days_expire * 24 * 60 * 60
    expires = datetime.datetime.strftime(datetime.datetime.utcnow(
    ) + datetime.timedelta(seconds=max_age), "%a, %d-%b-%Y %H:%M:%S GMT")
    response.set_cookie(key, value, max_age=max_age, expires=expires,
                        domain=settings.SESSION_COOKIE_DOMAIN, secure=settings.SESSION_COOKIE_SECURE or None)

Login/templates/Login/index.html
{% load  staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>COLDWHERE EDI LOGIN</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static  'Login/assets/images/icons/favicon.ico'  %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/vendor/bootstrap/css/bootstrap.min.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/fonts/font-awesome-4.7.0/css/font-awesome.min.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/fonts/iconic/css/material-design-iconic-font.min.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/vendor/animate/animate.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/vendor/css-hamburgers/hamburgers.min.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/vendor/animsition/css/animsition.min.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/vendor/select2/select2.min.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/vendor/daterangepicker/daterangepicker.css'  %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/css/util.css'  %}">
	<link rel="stylesheet" type="text/css" href="{% static  'Login/assets/css/main.css'  %}">
<!--===============================================================================================-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 


</head>
<body style="background-color:#22252a;">
	{% if error %}
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
		<script>
		swal("Authentication", "Invalid Credentials", "error");
		</script>
		{% endif %}

		{% if warning %}
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
		<script>
		swal("Server Error", "Try Again", "info");
		</script>
		{% endif %}
	<div class="limiter" >
		<div class="container-login100" >
			<div class="wrap-login100">
				<form class="login100-form validate-form" method = "POST" action = "{% url 'login:index' %}">
				{% csrf_token %}
					<span class="login100-form-logo">
						<i class="zmdi zmdi-landscape"></i>
					</span>

					<span class="login100-form-title p-b-34 p-t-27">
						COLDWHERE-EDI
					</span>

					<div class="wrap-input100 validate-input" data-validate = "Enter your email">
						<input class="input100"  id="login-email" type="text" name="username" placeholder="Email">
						<span class="focus-input100" data-placeholder="&#xf207;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="Enter password">
						<input class="input100" id="login-password" type="password" name="pass" placeholder="Password">
						<span class="focus-input100" data-placeholder="&#xf191;"></span>
					</div>

					

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" id="login">
							Login
						</button>
					</div>


				</form>
			</div>
		</div>
	</div>


	<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="{% static  'Login/assets/vendor/jquery/jquery-3.2.1.min.js'  %}"></script>
<!--===============================================================================================-->
	<script src="{% static  'Login/assets/vendor/animsition/js/animsition.min.js'  %}"></script>
<!--===============================================================================================-->
	<script src="{% static  'Login/assets/vendor/bootstrap/js/popper.js'  %}"></script>
	<script src="{% static  'Login/assets/vendor/bootstrap/js/bootstrap.min.js'  %}"></script>
<!--===============================================================================================-->
	<script src="{% static  'Login/assets/vendor/select2/select2.min.js'  %}"></script>
<!--===============================================================================================-->
	<script src="{% static  'Login/assets/vendor/daterangepicker/moment.min.js'  %}"></script>
	<script src="{% static  'Login/assets/vendor/daterangepicker/daterangepicker.js'  %}"></script>
<!--===============================================================================================-->
	<script src="{% static  'Login/assets/vendor/countdowntime/countdowntime.js'  %}"></script>
<!--===============================================================================================-->
	<script src="{% static  'Login/assets/js/main.js'  %}"></script>
	<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script>
var checkingStatus = false ;
    $( document ).ready(function() {
    refreshing();
	$('input[type="checkbox"]').click(function(){
		if($(this).prop("checked") == true)
		 checkboxStatus = true ;
		else if($(this).prop("checked") == false)
		 checkboxStatus = false ;
	});
  });
  function refreshing(){
  document.getElementById('login-email').focus();
  document.getElementById('login-email').value = '';
  document.getElementById("login-password").disabled = true;
  
  document.getElementById("login").disabled=true;
  }
  $('#login-email').on('keyup',function(){
        // vaidating input.
        var email = $(this).val();
		var password = $("#login-password"). val();
        // if (isEmail(email) && (email.length >0)) {
		//  document.getElementById("login-password").disabled = false;
		// }
		if ( (email.length >0)) {
		 document.getElementById("login-password").disabled = false;
		}

	// email is null , password entered , checkbox checked.
		else if  ((email.length  == 0) && (password.length > 0) && (checkboxStatus)){
			document.getElementById("login-password").disabled = false;
			
			 document.getElementById("login").disabled=true;
		}
		// email is null , password entered , checkbox not checked.
		else if  ((email.length  == 0) && (password.length > 0) && (!checkboxStatus)){
			document.getElementById("login-password").disabled = false;
			
			 document.getElementById("login").disabled=true;
		}
		 // email null , password null ,
		else if  ((email.length  == 0) && (password.length ==  0)){
			document.getElementById("login-password").disabled = true;
			
			 document.getElementById("login").disabled=true;
		}
 });

 $('#login-password').on('keyup',function(){
        var password = $(this).val();
		var email = $("#login-email"). val();
        if ((password.length >0) && (email.length >0)) {
		
		  document.getElementById("login").disabled=false;
		}
		else  if ((password.length == 0) ){
	
		 document.getElementById("login").disabled=true;
		}

 });
 function isEmail(email) {
  var regex = /^([a-zA-Z0-9_.+-])+\@(([a-zA-Z0-9-])+\.)+([a-zA-Z0-9]{2,4})+$/;
  return regex.test(email);
}
  </script>
</body>
</html>