DjangoEdi/urls.py
from django.contrib import admin
from django.urls import include, path
from service.views import tcpRequest
from main.views import startingThreads
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include("Login.urls")),
    path('index/', include("main.urls")),
]


try:
    print ("hello-1")
    startingThreads(repeat=5)
except KeyboardInterrupt:
    print("Service Ended !! ")


# try:
#     print ("hello-2")
#     statusReports(repeat=300)
# except KeyboardInterrupt:
#     print("Service Ended !! ")

main/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'main'
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^creatingAccount/$', views.accountCreation, name="account"),
    url(r'^statusReport/$', views.statusReport, name="report"),
    url(r'^companyActiveLoads/$', views.activeLoads, name="activeLoads"),
    url(r'^logout$', views.logout, name="logout"),
    url(r'^generatingReport/$', views.generatingReport, name="generating_report"),
    url(r'^statusPaths/$', views.creatingStatusPaths, name="status_paths"),
    url(r'^loadsPaths/$', views.creatingLoadPaths, name="load_paths"),
    url(r'^establishingConnection/$', views.establishingConnection, name="establishingConnection"),
]

main/models.py
from django.db import models


class accountRegistration(models.Model):

    ipHost = models.CharField(max_length=250)
    userName = models.CharField(max_length=500)
    password = models.CharField(max_length=100)
    email = models.CharField(max_length=500)
    input_path = models.CharField(max_length=1000)
    output_path = models.CharField(max_length=1000)
    ip_hostOut = models.CharField(max_length=250)
    user_nameOut = models.CharField(max_length=1000)
    passwordOut = models.CharField(max_length=1000)

    def __str__(self):
        return self.userName + " - " + self.ipHost

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.template import loader
import threading
import queue
import ftplib
import time
import json
import socket
import io
import requests
import json
from service.views import tcpRequest
from statusService.views import statusReports
from viewLoads.views import viewLoads
from background_task import background


@background(schedule=3)
def startingThreads():
    print ("inside here")
    thread_loadService = threading.Thread(
            target=loadServices)
    thread_statusSerivce = threading.Thread(
            target=statusSerivces)
    thread_viewLoad = threading.Thread(
            target=viewAllLoads)

    
    thread_loadService.start()
    thread_statusSerivce.start()
    thread_viewLoad.start()
    
    thread_loadService.join()
    thread_viewLoad.join()
    thread_statusSerivce.join()
    
def loadServices():
    tcpRequest()

def statusSerivces():
    statusReports()

def viewAllLoads():
    viewLoads()

# it is used to fetch all the companies on the reqyuest of the super admin .

def countingAccounts(request):
    try:
        url = "http://54.245.173.223:3000/account/countingCompanies"
        payload = ""
        headers = {
            'cache-control': "no-cache",
            }
        response = requests.request("POST", url, data=payload, headers=headers)
        python_dict =  json.loads(response.text)
        return python_dict.get("dataCount", "empty")

    except Exception as e:
        pass 
def accountDetails(request):
    try:
        url = "http://54.245.173.223:3000/account/"

        payload = ""
        headers = {
            'cache-control': "no-cache",
            }

        response = requests.request("GET", url, data=payload, headers=headers)
        python_dict =  json.loads(response.text)
        return python_dict.get("data", "empty")        
    except Exception as e:
        pass 
def fetchingCompanies(request):
    try:
        url = "http://35.167.129.201:8081/company/allcompanies"

        payload = ""
        headers = {
            'Authorization': "Bearer "+request.session['token'],
            'cache-control': "no-cache",
            'Content-Type': "application/json",
            
            }

        response = requests.request("GET", url, data=payload, headers=headers)
        python_dict =  json.loads(response.text)
        
        if (python_dict.get("status", "empty") == "Success"):
            return python_dict.get("details", "empty")
            
    except Exception as e:
        pass     
    # it is used to fetch the loads of a specfic company
def fetchingLoads(request , companyEmail):
    try:
        url = "http://35.167.129.201:8081/load/companyloadnumbers"

        data = {'company_email': companyEmail }
        payload = json.dumps(data)
        headers = {
            'Content-Type': "application/json",
            'Authorization': "Bearer "+request.session['token'],
            'cache-control': "no-cache",
            
            }

        response = requests.request("POST", url, data=payload, headers=headers)

        python_dict =  json.loads(response.text)


        if (python_dict.get("status", "empty") == "Success"):
            return python_dict.get("details", "empty")
    except Exception as e:
        pass 
def activeConnections(request, session_name):
    try:
        url = "http://54.245.173.223:3000/account/countingCompanies"
        payload = ""
        headers = {
            'cache-control': "no-cache",
            }

        response = requests.request("POST", url, data=payload, headers=headers)
        python_dict =  json.loads(response.text)
        request.session[session_name] = python_dict.get("dataCount", "empty")
    except Exception as e:
        pass 
    

def ConnectedConnections(request, session_name,  accounts):

    connected_connections = 0
    for i in range(len(accounts.get("data", "empty"))):
        try:
            ftp = ftplib.FTP((accounts.get("data", "empty"))[i].get ("ipHost"),
            (accounts.get("data", "empty"))[i].get ("userName"), 
            (accounts.get("data", "empty"))[i].get ("password"))
            if  (is_connected):
                connected_connections += 1
        except Exception as e:
            pass
    request.session[session_name] = connected_connections


def decryptedFiles(request, session_name,  accounts):
    decrypted_files_number = 0
    for i in range(len(accounts.get("data", "empty"))):
        ftp = ftplib.FTP((accounts.get("data", "empty"))[i].get ("ipHost"),
        (accounts.get("data", "empty"))[i].get ("userName"), 
        (accounts.get("data", "empty"))[i].get ("password"))

        folderpath = (accounts.get("data", "empty"))[i].get ("output_path")
        files = checkingDirectory(ftp, folderpath)
        # decrypted_files = ftp.nlst(folderpath)
        # decrypted_files.remove(".")
        # decrypted_files.remove("..")
        decrypted_files_number = decrypted_files_number + files
    request.session[session_name] = decrypted_files_number 


def sucessfulFiles(request, session_name,  accounts):
    sucessful_files_number = 0
    try:
        for i in range(len(accounts.get("data", "empty"))):
            ftp = ftplib.FTP((accounts.get("data", "empty"))[i].get ("ipHost"),
            (accounts.get("data", "empty"))[i].get ("userName"), 
            (accounts.get("data", "empty"))[i].get ("password"))     
            folderpath = (accounts.get("data", "empty"))[i].get ("input_path") + "/sucessful"
            files = checkingDirectory(ftp, folderpath)
            sucessful_files_number = sucessful_files_number + files
        request.session[session_name] = sucessful_files_number 
    except Exception as e:
        request.session[session_name] = "0"
    
def checkingDirectory(ftp,folderpath):

    files = []
    try:
        files = ftp.nlst(folderpath)
        files.remove(".")
        files.remove("..")
        return len(files)      
    except Exception as e:
        return 0
    
def company_FtpAccounts(request, session_name, accountDetail):
    try:
        if(accountDetail.get("ipHost", "empty") == accountDetail.get("ip_hostOut", "empty")):
            request.session[session_name] = "1"
        elif(accountDetail.get("ipHost", "empty") != accountDetail.get("ip_hostOut", "empty")):
            request.session[session_name] = "2"
    except Exception as e:
        request.session[session_name] = "0"


def company_files(request, accountDetail, folder):
    try:
        ftp = ftplib.FTP(accountDetail.get("ipHost", "empty"), accountDetail.get("userName", "empty"),
                         accountDetail.get("password", "empty"))

        if (folder == "output"):
            folderpath = accountDetail.get("output_path", "empty")
        elif (folder == "sucessful"):
            folderpath = accountDetail.get("input_path", "empty") + "/sucessful"
        elif (folder == "notSucessful"):
            folderpath = accountDetail.get("input_path", "empty") + "/notSucessful"

        files = ftp.nlst(folderpath)
        files.remove(".")
        files.remove("..")
        request.session[folder] = len(files) 
        output_files = []
        for file in files:
            output_files.append(file)

        request.session["output_files"] = output_files
        request.session["ftp_username"] = accountDetail.get("userName", "empty")
        request.session["output_path"] = accountDetail.get("output_path", "empty")
    except Exception as e:
        request.session[folder] = "0"

def fetchingStatus(request):
    try:
        url = "http://35.167.129.201:8081/user/me"

        payload = ""
        headers = {
            'Authorization': "Bearer "+request.session['token'],
            'cache-control': "no-cache",
            
            }

        response = requests.request("GET", url, data=payload, headers=headers)
        python_dict =  json.loads(response.text)
        if (python_dict.get("status", "empty") == "Success"):
            if(python_dict.get("details", "empty").get("role") == "user"):
                request.session['name'] = python_dict.get("details", "empty").get("company_email")
            
            return (python_dict.get("details", "empty").get("role"))
        else:
            return ("INVALID CREDENTIALS")
    except Exception as e:
        pass    


def index(request):
    # """ Index page, after login """

    if request.method == "GET":
        try:   
            request.session['role'] = fetchingStatus(request)
        
            if ((request.session['role'] == "company") or ((request.session['role'] == "user"))):
                # deletingSessions (request ,["ftpAccounts","output","sucessful","notSucessful"])
                response = fetchingCompanyTilesData(request)
                if (response == "noerror"):
                    comapny_tiles_data = {
                        "ftp_accounts": request.session["ftpAccounts"],
                        "decrypted_files": request.session["output"],
                        "sucessful_files": request.session["sucessful"],
                        "unSucessful_files": request.session["notSucessful"],
                    }
                elif(response == "error"):
                    comapny_tiles_data = {
                        "ftp_accounts": "0",
                        "decrypted_files": "0",
                        "sucessful_files": "0",
                        "unSucessful_files": "0",
                    }

                return render(request, 'main/edi_indexCompany.html', {'tiles_data':  comapny_tiles_data})
            elif(request.session['role'] == "super_admin"):
                
                response = fetchingUserTilesData(request)
                dropdown_data = fetchingCompanies(request)
                
                if (response == "noerror"):
                    tiles_data = {

main/templates/main/allStatusReports.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ColdWhere-EDI</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="{% static  'main/assets/vendor/bootstrap/css/bootstrap.min.css'  %}">

    <link rel="stylesheet" href="{% static  'main/assets/vendor/font-awesome/css/font-awesome.min.css'  %}">
    <!-- Custom Font Icons CSS-->
    <link rel="stylesheet" href="{% static  'main/assets/css/font.css'  %}">

    <!-- Google fonts - Muli-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli:300,400,700">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static  'main/assets/css/style.default.css'  %}">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static  'main/assets/css/custom.css'  %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static  'main/assets/img/favicon.ico'  %}">

    <style>

        .block{

 margin-top:132px;
 }

#comapnyname option {
background: #555555;
}

#activeloads option {
background: #555555;
}


 </style>
</head>

<body>
    <header class="header">
        <nav class="navbar navbar-expand-lg">

            <div class="container-fluid d-flex align-items-center justify-content-between">
                <div class="navbar-header">
                    <!-- Navbar Header--><a href="{% url 'main:index' %}" class="navbar-brand">
                        <div class="brand-text brand-big visible text-uppercase"><strong class="text-primary">Cold</strong><strong>Where</strong></div>
                        <div class="brand-text brand-sm"><strong class="text-primary">C</strong><strong>W</strong></div>
                    </a>
                    <!-- Sidebar Toggle Btn-->
                    <button class="sidebar-toggle"><i class="fa fa-long-arrow-left"></i></button>
                </div>
                <div class="right-menu list-inline no-margin-bottom">


                    <!--Logout-->
                    <div class="list-inline-item logout"> <a id="logout" href="{% url 'main:logout' %}" class="nav-link">Logout <i class="icon-logout"></i></a></div>
                </div>
            </div>
        </nav>
    </header>
    <div class="d-flex align-items-stretch">
        <!-- Sidebar Navigation-->
        <nav id="sidebar">

            <!-- Sidebar Navidation Menus--><span class="heading">Main</span>
            <ul class="list-unstyled">
                <li><a href="{% url 'main:index' %}"> <i class="icon-home"></i>Home </a></li>
                <li class="active"><a href="#exampledropdownDropdown" aria-expanded="false" data-toggle="collapse"> <i class="icon-windows"></i>Settings</a>

                    <ul id="exampledropdownDropdown" class="collapse list-unstyled ">
                        <li ><a href="{% url 'main:account' %}">Account Creation</a></li>
                            <li class="active"><a href="#">Status Report</a></li>

                    </ul>
                </li>

        </nav>
        <!-- Sidebar Navigation end-->
        <div class="page-content">
            <div class="page-header">
                <div class="container-fluid">
                    <h2 class="h5 no-margin-bottom">EDI Status Report</h2>
                </div>
            </div>
            <!-- Breadcrumb-->
            <div class="container-fluid">

            </div>

            <section class="no-padding-top">
                <div class="container-fluid">
                    <div class="row">
                        <!-- Basic Form-->
                        <div class="col-lg-8 offset-lg-2">
                            <div class="block">
                                <div class="block-body">
                                  
                                    <form name = "submitting-form">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label class="form-control-label" for="comapnyname">Company Name</label>
                                            <div class="input-group-prepend">
                                                <select name="comapnyname"  id = "comapnyname" class="form-control col-lg-12">
                                                    <option value="selectedvalue" selected disabled>Select a company</option>
                                                    {% for value in dropdown%}
                                                    <option value={{value.email}}>{{value.name}}</option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </div>
                                       
                     <div class="form-group">
                       <label class="form-control-label" for = "inputpath">Input Path</label>
                       <input type="text" id ="inputpath" placeholder="Path where you will request for the shipment" class="form-control">
                     </div>
                     <div class="form-group">
                       <label class="form-control-label" for= "outputpath">Output Path</label>
                       <input type="text" id= "outputpath" placeholder="Path where your status report will be generated" class="form-control">
                     </div>
                                        <center>
                                            <div class="form-group">
                                                <input type="button" id="status" value="Create" class="btn btn-primary">
                                            </div>
                                        </center>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
            </section>
            <footer class="footer">
                <div class="footer__block block no-margin-bottom">
                    <div class="container-fluid text-center">
                        <!-- Please do not remove the backlink to us unless you support us at https://bootstrapious.com/donate. It is part of the license conditions. Thank you for understanding :)-->
                        <p class="no-margin-bottom">2019 &copy; Design by <a href="https://www.coldwhere.com/">ColdWhere</a>.</p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static  'main/assets/vendor/jquery/jquery.min.js'  %}"></script>
    <script src="{% static  'main/assets/vendor/popper.js/umd/popper.min.js'  %}"> </script>
    <script src="{% static  'main/assets/vendor/bootstrap/js/bootstrap.min.js'  %}"></script>
    <script src="{% static  'main/assets/vendor/jquery.cookie/jquery.cookie.js'  %}"> </script>

    <script src="{% static  'main/assets/vendor/jquery-validation/jquery.validate.min.js'  %}"></script>
    <script src="{% static  'main/assets/js/charts-home.js'  %}"></script>
    <script src="{% static  'main/assets/js/front.js'  %}"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
	
    <script>
    $( document ).ready(function() {
    disablingFields(["inputpath", "outputpath","status"])
    $('#comapnyname').change(function () {
        disablingEmptyFields(["inputpath","outputpath"]);
        selectVal = $('#comapnyname').val();
        if (selectVal != "selectedvalue") {
        console.log(selectVal)    
        connecting_ftpAccount(selectVal)
   }
}) // event handler of the drop down ends.

 // keeping track of the other dropdown.
}); // ready func .
$("#status").click(function(){
    generatingReport();
});

function connecting_ftpAccount(email){
    $.ajax({
        url :  "{% url 'main:establishingConnection' %}",
        type: "post",
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}' ,
            "email":email,

        },
        success: function(response) {
            console.log(response)
            if( response !== "No Ftp Account is associated with it."){
                document.getElementById("inputpath").disabled = false;
            }
            else {
                swal("FTP Account!", "You dont have any FTP Account associated with this company", "error")
                         
            }
        },
        error: function(jqXHR, textStatus, errorThrown){
            swal("FTP Account!", "You dont have any FTP Account associated with this company", "error")

}

        
}) // ajax call ends
}
// generating report
function generatingReport(){
    $.ajax({
        url :  "{% url 'main:status_paths' %}",
        type: "post",
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}' ,
            "inputpath": $("#inputpath").val(),
            "outputpath":$("#outputpath").val(),
        },
        success: function(response) {
            console.log (response)
            if (response === "Success"){
              swal("Status Directory!", "Status Directories has been created", "success")
             }
             else if (response === "Error") {
              swal("Status Directory!", "Status Directories already exists", "error")
             }
         
           var full_form = document.getElementsByName('submitting-form')[0];
                            full_form.reset();
        },
        error: function(jqXHR, textStatus, errorThrown){
           alert("Some thing went wrong.")
}
}) // ajax call ends
}
function disablingFields(textfields){
 	for (i = 0; i < textfields.length; i++) {
	document.getElementById(textfields[i]).disabled=true;
		}
 }

 function enablingField(textfields){
   for (i = 0; i < textfields.length; i++) {
	if ((!document.getElementById(textfields[i]).value) && (!document.getElementById(textfields[i]).disabled )) {
		break;
		}

	else if ((!document.getElementById(textfields[i]).value) && document.getElementById(textfields[i]).disabled ) {
		document.getElementById(textfields[i]).disabled=false;
		break;
		}

   }
  }
  function disablingEmptyFields(textfields){
  	for (i = 0; i < textfields.length; i++) {
 	if (!document.getElementById(textfields[i]).value )
 	document.getElementById(textfields[i]).disabled=true;
 		}
  }
  function validatingAboveFields(textfields){
       var checkingStatus = false;
  	   for (i = 0; i < textfields.length; i++) {
  		textfield = $(textfields[i]).val().trim()
    // checking  the fields .
    if ((textfield.length) > 0) {
  		checkingStatus = true ;
  		}
  	else if ((textfield.length) < 0) {
  		checkingStatus = false ;
  		break ;
  		}
     }
  	return checkingStatus;
  	}


 function populatingDropdowns(){
     $.ajax({
         url :  "{% url 'main:report'%}",
         type: "post",
         data: {
             csrfmiddlewaretoken: '{{ csrf_token }}' ,
             company_email: $('#comapnyname').val().trim(),
         },
         success: function(response) {
             console.log(response)
             var select = document.getElementById("activeloads");
             for(var i=0;i<response.dropdown.length; i++){
              var option_element = document.createElement("option");
             option_element.textContent = response.dropdown[i].load_number;
             option_element.value =  response.dropdown[i].id_device_load_record;
             select.appendChild(option_element);
     }
         select.disabled=false;
         },
         error: function(jqXHR, textStatus, errorThrown){
            alert("Some thing went wrong.")
 }

 }) // ajax call ends
 }
  // validating fields

       $('#inputpath').on('keyup',function(){
               var textvalue = $(this).val().trim();
               if ((textvalue.length >0) ) {
                 enablingField(["outputpath"]);
       		}
       		else if ((textvalue.length  == 0)) {
             disablingEmptyFields(["outputpath"]);
       		}
        });

        $('#outputpath').on('keyup',function(){
                var textvalue = $(this).val().trim();
        		var status = validatingAboveFields(["#inputpath"]);
                if ((textvalue.length >0) && status ) {
                    document.getElementById("status").disabled = false;
        		}
        		else if ((textvalue.length  == 0)) {
                        document.getElementById("status").disabled = true;
        		}
         });

    </script>


</body>

</html>